version: '3.4'

services:

  db:
    image: "mdillon/postgis:11"
    environment:
      # Must duplicate due to limitations of docker-compose:
      POSTGRES_DB: of-arena-dev
      POSTGRES_USER: arena
      POSTGRES_PASSWORD: arena

  app_server:
    env_file:
      - ../.env
    depends_on:
      - db
    ports:
      - "9990:9090"
    build:
      context: ..
      dockerfile: Dockerfile
      target: arena-server

    environment:
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: of-arena-dev
      PGUSER: arena
      PGPASSWORD: arena
      TEMP_FOLDER: /tmp/arena_upload
      ANALYSIS_OUTPUT_DIR: /tmp/arena_analysis

    # Start application server when Postgres is ready:
    command: "sh -c '
      apt update;
      apt-get install -y netcat;
      while ! nc -z $$PGHOST $$PGPORT; do sleep 0.1; done;
      exec pm2-runtime server.js
    '"

  web:
    env_file:
      - ../.env
    depends_on:
      - app_server
    ports:
      - "9880:80"
    build:
      context: ..
      dockerfile: Dockerfile
      target: arena-web
    environment:
      ARENA_HOST: app_server:9090
